project:
  type: book

book:
  title: "STAT468 Final Project Report"
  author: "Keerthi Kiran"
  date: "2025-08-05"
  chapters:
    - index.qmd
    - 01-question.qmd
    - 02-import.qmd
    - 03-tidy.qmd
    - 04-transform.qmd
    - 05-visualize.qmd
    - 06-model.qmd
    - 07-communicate.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    code-fold: true  



