## References

- RStudio. (n.d.). *Using renv with Docker*. Retrieved from https://rstudio.github.io/renv/articles/docker.html
- OpenAI. (2025). *ChatGPT conversation share link*. Retrieved from https://chatgpt.com/c/689d23ee-0338-8329-a369-c7211e3d9364
- Posit Community Forum. (2025). *Vetiver problem with Docker*. Retrieved from https://forum.posit.co/t/vetiver-problem-with-docker/177789
- Nature. (2025). *Article in Scientific Data*. https://www.nature.com/articles/s41597-025-04505-y
- ArXiv. (2022). *Title: TBD*. Retrieved from https://arxiv.org/abs/2207.14124
- ResearchGate. (2024). *Engineering Features from Raw Sensor Data to Analyse Player Movements during Competition*. https://www.researchgate.net/publication/378318969_Engineering_Features_from_Raw_Sensor_Data_to_Analyse_Player_Movements_during_Competition
- ResearchGate. (2009). *Multicollinearity in regression models with multiple distance measures*. https://www.researchgate.net/publication/229748502_Multicolinearity_in_regression_models_with_multiple_distance_measures
- DataCamp. (n.d.). *Variance Inflation Factor*. Retrieved from https://www.datacamp.com/tutorial/variance-inflation-factor
- OpenAI. (2025). *ChatGPT conversation share link*. Retrieved from https://chatgpt.com/c/689cf8c9-a570-8327-bbab-c76401976cb0
- University of Waterloo. (n.d.). *Logistic Regression with R*. Retrieved from https://uwaterloo.ca/statistical-consulting-survey-research-unit/sites/default/files/uploads/documents/logistic_regression_with_r.pdf
- Posit. (n.d.). *Vetiver: Deploy with Docker*. Retrieved from https://vetiver.posit.co/learn-more/deploy-with-docker.html
- Penn State University. (n.d.). *STAT 462: Logistic Regression*. Retrieved from https://online.stat.psu.edu/stat462/node/173/
- Technical University of Munich. (n.d.). *Lecture 5 Notes*. Retrieved from https://www.math.cit.tum.de/fileadmin/w00ccg/math/Forschung/forschungsgruppen/statistics/academics/lec5.pdf
- Posit. (n.d.). *Deploy with Docker: Create a Vetiver Model*. Retrieved from https://vetiver.posit.co/learn-more/deploy-with-docker.html#create-a-vetiver-model
- Posit. (n.d.). *Share your Shiny app*. Retrieved from https://shiny.posit.co/r/articles/share/shinyapps/
- AWS. (n.d.). *AWS Management Console*. Retrieved from https://us-east-2.console.aws.amazon.com/console/home?nc2=h_uta_mc&region=us-east-2
- Posit. (n.d.). *Shiny layout guide*. Retrieved from https://shiny.posit.co/r/articles/build/layout-guide/
- Olympics.com. (n.d.). *Badminton court size, dimensions, and measurements*. Retrieved from https://www.olympics.com/en/news/badminton-court-size-dimension-measurement-length-width-net-height-service-line
- OpenAI. (2025). *ChatGPT conversation share link*. Retrieved from https://chatgpt.com/share/689d5c38-64f8-8001-8ceb-52d47fbbe0a4
