# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_s3(bucket = "stat-468-cleaned-data", region = structure("us-east-2", tags = list(type = "scalar")))
v <- vetiver_pin_read(b, "chou_model", version = "20250814T041848Z-4ce06")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
